services:
  jenkins:
    image: jenkins:lts-python
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_init:/usr/share/jenkins/ref/init.groovy.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_BUILDKIT=1
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
volumes:
  jenkins_home:
